version: '3.1'

services:
  vmware-integration-with-mock:
    container_name: vmware-integration-with-mock
    build:
      context: ../
      dockerfile: ./integration-test/Dockerfile
    ports:
       - "8989:8989"
    entrypoint: "/go/src/github.com/vmware/govmomi/vcsim/vcsim -l :8989 -load /go/src/github.com/newrelic/nri-vmware-vsphere/integration-test/my-vcenter"

