name: Security vulnerabilities scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/github.com/newrelic/nri-vsphere
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        GOPATH: /github/workspace
      with:
        args: /github/workspace/src/github.com/newrelic/nri-vsphere --severity-threshold=high
        command: test

        